services:
  db:
    image: docker.io/library/postgres:16
    env_file:
      - ./kino-webb/.env.local
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
